=== polinaLap/-JavaExternal_06_03_2018/26_04_DataBasePr/lessons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.javacourses.ua/lessons"
        xmlns:tns="http://www.javacourses.ua/lessons"
        elementFormDefault="qualified">
    <element name="lessons">
        <complexType>
            <sequence>
                <element name="lesson"
                         type="tns:Lesson"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Lesson">
        <sequence>
            <element name="id" type="positiveInteger" />
            <element name="name" type= "string"/>
        </sequence>
    </complexType>
</schema>

=== polinaLap/-JavaExternal_06_03_2018/26_04_DataBasePr/lessons.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lessons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.javacourses.ua/lessons"
         xsi:schemaLocation="http://www.javacourses.ua/lessons lessons.xsd">
    <lesson>
        <id>1</id>
        <name>Math</name>
    </lesson>
    <lesson>
        <id>2</id>
        <name>Ukr</name>
    </lesson>
    <lesson>
        <id>3</id>
        <name>Physics</name>
    </lesson>
    <lesson>
        <id>4</id>
        <name>Chemistry</name>
    </lesson>
    <lesson>
        <id>5</id>
        <name>Geography</name>
    </lesson>
</lessons>
